cache:
  npm: true
  directories:
    - "node_modules"
    
language: node_js
install:
  - npm install
  - npm upgrade

script:
  - rm -R *
  - git clone --single-branch --branch login_frontend https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-frontend.git
  - cp -R shop-frontend/* $TRAVIS_BUILD_DIR/
  - sudo rm -R shop-frontend
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-tests.git
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-backend.git
  - cp -R shop-tests/frontend $TRAVIS_BUILD_DIR/tests/
  - sudo rm -R shop-tests
  - npm run-script build 
  - sudo rm -R !(build || node_modules)
  - mv build/* $TRAVIS_BUILD_DIR/
  - sudo rm -R build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: shop-354
  on: dev-demo
  skip_cleanup: true
