language: node_js
cache:
  npm: true
  directories:
    - node_modules
before_install:
  - nvm install v10.16.2
install:
  - npm install
  - composer install
script:
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-backend.git
  - sudo mv shop-backend/php/* public/
deploy:
  provider: heroku
  api_key:
    secure: sYbAT6kL4uiO8JYWa/CUxXKv+FXGrJ/5xa1WIiQBpnMjC1JSLqGDm8ETTs29p4kdPHE3szW/Eabn7Y/8g8HOuXS2JDJOGIYMzmjYAJRS87Pb8YCLkWdkfXT4sTbVlVlOZi/fgMBnZLVYvlg5o2aKOGk9JUnVwDSSEenmiwQQIwActzgVkrz/Nx2vO5sGCGDXXoKt/8B/gbhOAMDPlnNEqsH6PDPKYjpMdiUUTKl0xsCoYDRsECho8jo+UB72gHR4lKMhb0pE+0J7VNr+9Zjrm5DsbI9U8wJunt03y+YkejplwtNJP8/bM7usgn0CaCplXxctSIVuhA/N8gNS2RWahl8U18a6vwyebZS90FbrloD6q/+y1tO0nnO2xC6H580m+glwoUC+aLf2ae5n0x0v1dXbLfLD58eKhg/2HHQ4sLmbtOrv4lqwcKzYEw5EX9Bbfa9Vsg8k9KoSMphlAxiPUYsk/OdegvDgqh+jTvrnFqLDRtxQbAbQ1THoOhudgPLMJUcLqGYHFJ4sKhk+b92DeTg1oL8Ndp96JvdxXW+LdA+xHehSNvxmIl5k33dEjXJOP9RMmjyKtKlk+ARCpl3S44FA1czeDwrCZK2aI9PIc2VHFE+PKL7SNcF0IG420/H637yYDskpAcBumguHCxWCOZANd0zUelM9bt/8lE0kRTQ=
  app: shop-354-backend
  on: test-merge
  skip_cleanup: true
