cache:
  npm: true
  directories:
    - "node_modules"
    
language: node_js
node:
  - 10
install:
  - npm install
  - npm upgrade

script:
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-tests.git
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-backend.git
  - cp -R shop-tests/frontend $TRAVIS_BUILD_DIR/tests/
  - sudo rm -R shop-tests
  - ls
  - npm build 
  - ls
  - sudo rm -R !(build)
  - ls
  - mv build/* $TRAVIS_BUILD_DIR/
  - sudo rm -R build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: shop-354
  on: dev-demo
  skip_cleanup: true
