language: node_js
cache:
  npm: true
  directories:
    - node_modules
before_install:
  - nvm install v10.16.2
install:
  - npm install
script:
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-tests.git
  - git clone https://$GITHUB_TOKEN@github.com/SparrowOchon/shop-backend.git
  - sudo mv shop-backend/ public/
  - cp -R shop-tests/frontend $TRAVIS_BUILD_DIR/tests/
  - rm -R tests/
  - unset CI
  - npm run-script build
  - sudo rm -R shop-tests
  - sudo rm -R node_modules
  - sudo rm -R build/
deploy:
  provider: heroku
  api_key:
    secure: 2YBgbS/yYbYM5WA2FAXuFyvVOn4VKV2S2M9/owh6+snsPOutyNdVp6YcvoiC6HJCVeDVGqGew+IQKUFW/PAFihAyzHL3yQW/y3lOtsALCNbsJnTdhNfdqur4i5T8aSQ1kj26l2IkD817rYi6r3Mkz13ZFW0EtOtUnZpYD7yzpNDtmsFiGYtHvM9VuOl8UBzkn5hwWzbA24I2xJJHZaeDBKULhBZeLhp34zkdxjlFp/er4SaGu1XgK2J72JsyNcuGNM+MUyCuKeYN7uKQBS1PsApxsNE3YOIlilRcep27HgSjcUZiFx3MsnYf2HE2kPGxbqvNUoAtCMWgbhKgLSNH8U77loCSkNdm2x5qB6H9rKrbjt6EBgds0VS7R0lfD/BAFwPYE1TvisHCuZk+Jz6+jdPXAapcCctJzNUQek80iIDB0/QSALkQve5CsDg5NsVBxXPuEW8/yMnYcCFPR/0OATHFHhjvPykRrrgIo5Ze5/1DtVTffcyEaw2EX+Nh+W74j3bEDIh1KcQfJNBauezyV84vu21OnmfSvWOk6QnQtiGW1VPw3D4X1GNadQt+joJAssAqT57NJQIN9MOFwP3umMD3aKJlMu+sEJSUGY0qir37K5YxXQncA0kXNq+bRbV1UodFd5n1bsFRC/85sEWgJBE5xPsIIIeYpW/UESrGEgA=
  app: shop-354
  on: master
  skip_cleanup: true
